backend:
  name: git-gateway
  branch: netlify
  publish_mode: editorial_workflow
  
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Author"
        name: "author"
        widget: "string"

      - label: "Date"
        name: "date"
        widget: "datetime"

      - label: "Body"
        name: "body"
        widget: "markdown"

- name: "actu"
    label: "Actualités"
    folder: "content/actu"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Author"
        name: "author"
        widget: "string"

      - label: "Date"
        name: "date"
        widget: "datetime"

      - label: "Body"
        name: "body"
        widget: "markdown"
